[package]
name = "sqlx-example-postgres-listen"
version = "0.1.0"
edition = "2018"
workspace = "../../../"

[dependencies]
async-std = { version = "1.4.0", features = [ "attributes", "unstable" ] }
sqlx = { path = "../../../", features = [ "postgres", "tls" ] }
futures = "0.3.1"
